
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: ghcr.io/minhdn1711/webapp_ql_chi_tieu-backend:main
    container_name: couple-expense-backend
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    expose:
      - "3000"
    networks:
      - miliwebseo_shared
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/minhdn1711/webapp_ql_chi_tieu-frontend:main
    container_name: couple-expense-frontend
    depends_on:
      - backend
    env_file:
      - .env
    expose:
      - "80"
    networks:
      - miliwebseo_shared
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    restart: always

networks:
  miliwebseo_shared:
    external: true
